# Snakemake workdir - environments and output are written to this directory
output_directory: /prj/rpbp-dev/Maja_data_hIPSC_diff/comparison/benchmark/results

# Tools to benchmark
tools:
  - anota2seq
  - riborex
  - deltate
  - ribotools_lrt
  - ribotools_dte

# Input data (relative to parent, or absolute)
data:
  benchmark1:
    ribo: "data/Oertlin/ribo_counts.csv"
    rna: "data/Oertlin/rna_counts.csv"
    samples: "data/Oertlin/samples.csv"
    # labels must match evaluation script
    groundtruth:
      translation: "data/Oertlin/translation.txt"
      abundance: "data/Oertlin/abundance.txt"
      buffering: "data/Oertlin/buffering.txt"
  benchmark2:
    ribo: "data/Boileau/ribo_counts.csv"
    rna: "data/Boileau/rna_counts.csv"
    samples: "data/Boileau/samples.csv"

# TEA
params:
  benchmark1:
    fdr_threshold: 0.1
  benchmark2:
    fdr_threshold: 0.05
    # tools to exclude
    exclude:
      - anota2seq # n>3 required
      - riborex # no FDR, deprecated
      - deltate # ~ribotools_dte
      - ribotools_dte # ~ribotools_lrt

# Benchmarks - match input data, params, and Snakemake rules
benchmarks:
  - "benchmark1"
  - "benchmark2"
